#ifndef SMART_CARAVAN_COMMON_H
#define SMART_CARAVAN_COMMON_H
#include <Arduino.h>

#define COUNT_RELAY 16

#define PIN_RELAY_1 37
#define PIN_RELAY_2 36
#define PIN_RELAY_3 35
#define PIN_RELAY_4 34
#define PIN_RELAY_5 33
#define PIN_RELAY_6 32
#define PIN_RELAY_7 31
#define PIN_RELAY_8 30
#define PIN_RELAY_9 29
#define PIN_RELAY_10 28
#define PIN_RELAY_11 27
#define PIN_RELAY_12 26
#define PIN_RELAY_13 25
#define PIN_RELAY_14 24
#define PIN_RELAY_15 23
#define PIN_RELAY_16 22
#define PIN_TEMPERATURE_SENSOR_1 PIN_A0


#define COMMAND_KEY_1 1
#define COMMAND_KEY_2 2
#define COMMAND_KEY_3 3
#define COMMAND_KEY_4 4
#define COMMAND_KEY_5 5
#define COMMAND_KEY_6 6
#define COMMAND_KEY_7 7
#define COMMAND_KEY_8 8
#define COMMAND_KEY_9 9
#define COMMAND_KEY_10 10
#define COMMAND_KEY_11 11
#define COMMAND_KEY_12 12
#define COMMAND_KEY_13 13
#define COMMAND_KEY_14 14
#define COMMAND_KEY_15 15
#define COMMAND_KEY_16 16
#define COMMAND_KEY_DATA_SEND_TEMPERATURE_AND_HUMIDITY 18
#define COMMAND_KEY_DATA_SEND_ALL 98
#define COMMAND_KEY_DATA_RESET_RELAYS 99
#define COMMAND_KEY_DATA_SEND_RELAY_1 51
#define COMMAND_KEY_DATA_SEND_RELAY_2 52
#define COMMAND_KEY_DATA_SEND_RELAY_3 53
#define COMMAND_KEY_DATA_SEND_RELAY_4 54
#define COMMAND_KEY_DATA_SEND_RELAY_5 55
#define COMMAND_KEY_DATA_SEND_RELAY_6 56
#define COMMAND_KEY_DATA_SEND_RELAY_7 57
#define COMMAND_KEY_DATA_SEND_RELAY_8 58
#define COMMAND_KEY_DATA_SEND_RELAY_9 59
#define COMMAND_KEY_DATA_SEND_RELAY_10 60
#define COMMAND_KEY_DATA_SEND_RELAY_11 61
#define COMMAND_KEY_DATA_SEND_RELAY_12 62
#define COMMAND_KEY_DATA_SEND_RELAY_13 63
#define COMMAND_KEY_DATA_SEND_RELAY_14 64
#define COMMAND_KEY_DATA_SEND_RELAY_15 65
#define COMMAND_KEY_DATA_SEND_RELAY_16 66



#define DATA_KEY_RELAY_1 1
#define DATA_KEY_RELAY_2 2
#define DATA_KEY_RELAY_3 3
#define DATA_KEY_RELAY_4 4
#define DATA_KEY_RELAY_5 5
#define DATA_KEY_RELAY_6 6
#define DATA_KEY_RELAY_7 7
#define DATA_KEY_RELAY_8 8
#define DATA_KEY_RELAY_9 9
#define DATA_KEY_RELAY_10 10
#define DATA_KEY_RELAY_11 11
#define DATA_KEY_RELAY_12 12
#define DATA_KEY_RELAY_13 13
#define DATA_KEY_RELAY_14 14
#define DATA_KEY_RELAY_15 15
#define DATA_KEY_RELAY_16 16
#define DATA_KEY_RELAY_TEMPERATURE 17
#define DATA_KEY_RELAY_HUMIDITY 18

#endif
